###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    redis:
        image: 'redis:alpine'

    mysql:
        image: 'mysql:8.0'
        working_dir: /var/www
        volumes:
            - '.:/var/www'
            - './db:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=cosmo
            - MYSQL_DATABASE=cosmo
            - MYSQL_USER=cosmo
            - MYSQL_PASSWORD=cosmo
        ports:
            - '8082:3306'

    elasticsearch:
        image: 'elasticsearch:6.5.4'

    webserver:
        image: 'nginx:alpine'
        working_dir: /var/www
        volumes:
            - '.:/var/www'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /var/www
        volumes:
            - '.:/var/www'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
