name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Docker Compose
        uses: hoverkraft-tech/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
