name: Deploy buy runner

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: docker-compose
        run: docker-compose up -d