name: Build
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Docker Compose
        uses: hoverkraft-tech/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
      - name: UP
        run: docker compose up