name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build the stack
        run: docker-compose up -d --build